{{ if .Values.disruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
{{ toYaml .Values.disruptionBudget | indent 2 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
{{ end }}