apiVersion: v1
name: rethinkdb
description: The open-source database for the realtime web
version: 2.0.4
appVersion: 2.4.0
keywords:
- rethinkdb
- database
- nosql
home: https://www.rethinkdb.com
sources:
- https://hub.docker.com/r/codylundquist/helm-rethinkdb-cluster/
- https://github.com/rethinkdb/prometheus-exporter
icon: http://i.imgur.com/bZ75N6r.jpg
maintainers:
- name: meenie
  email: cody.lundquist@gmail.com
