{{if .Values.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "rethinkdb.fullname" . }}-exporter"
  labels:
    app: "{{ template "rethinkdb.name" . }}-exporter"
    chart: {{ template "rethinkdb.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.exporter.replicas }}
  selector:
    matchLabels:
      app: "{{ template "rethinkdb.name" . }}-exporter"
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: "{{ template "rethinkdb.name" . }}-exporter"
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.exporter.affinity }}
      affinity:
        {{ tpl .Values.exporter.affinity . | indent 8 | trim }}
      {{- end }}
      {{- if .Values.exporter.tolerations }}
      tolerations:
{{ toYaml .Values.exporter.tolerations | indent 6 }}
      {{- end }}
      containers:
        - name: "{{ template "rethinkdb.fullname" . }}-exporter"
          image: "{{ .Values.exporter.image.name }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9055
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          env:
            - name: DB_ADDRESSES
              value: "{{ template "rethinkdb.fullname" . }}-proxy:{{ .Values.ports.driver }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.rethinkdbPasswordSecret }}"
                  key: RETHINKDB_PASSWORD
          resources:
{{ toYaml .Values.exporter.resources | indent 12 }}
{{- end }}