{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "microfleet.fullname" . }}
  labels:
    app: {{ template "microfleet.fullname" . }}
    chart: {{ template "microfleet.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
{{ toYaml .Values.rbac.rules | indent 2 }}
{{- end -}}
