{{- if .Values.toolchain.gcpBackendPolicy -}}
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
{{ toYaml .Values.toolchain.gcpBackendPolicy | indent 2 }}
{{- end }}
