{{- if .Values.hpa -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microfleet.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "microfleet.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      {{- if .Values.hpa.cpu.targetAverageUtilization }}
      targetAverageUtilization: {{ .Values.hpa.cpu.targetAverageUtilization }}
      {{- end }}
      {{- if .Values.hpa.cpu.targetAverageValue }}
      targetAverageValue: {{ .Values.hpa.cpu.targetAverageValue }}
      {{- end }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      {{- if .Values.hpa.memory.targetAverageUtilization }}
      targetAverageUtilization: {{ .Values.hpa.memory.targetAverageUtilization }}
      {{- end }}
      {{- if .Values.hpa.memory.targetAverageValue }}
      targetAverageValue: {{ .Values.hpa.memory.targetAverageValue }}
      {{- end }}
  {{- end }}
  {{- if .Values.hpa.customMetrics }}
{{ toYaml .Values.hpa.customMetrics | indent 2 }}
  {{- end }}
{{- end }}