{{- if .Values.hpa -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microfleet.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "microfleet.fullname" . }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.cpu }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.hpa.memory }}
  {{- end }}
  {{- if .Values.hpa.customMetrics }}
  - type: Pods
    pods:
      metricName: {{ .Values.hpa.customMetrics.metricName }}
      targetAverageValue: {{ .Values.hpa.customMetrics.targetAverageValue }}
  {{- end }}
{{- end }}