{{- if .Values.hpa -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microfleet.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.kind }}
    name: {{ include "microfleet.fullname" . }}
  {{- if .Values.replicaCount }}
  minReplicas: {{ .Values.replicaCount | default 1 }}
  {{- else if .Values.hpa.minReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  {{- else }}
  minReplicas: 1
  {{- end }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- if .Values.hpa.cpu }}
  - type: Resource
    resource:
      name: cpu
      target:
        {{- if .Values.hpa.cpu.averageUtilization }}
        type: Utilization
        averageUtilization: {{ .Values.hpa.cpu.averageUtilization }}
        {{- end }}
        {{- if .Values.hpa.cpu.averageValue }}
        type: AverageValue
        averageValue: {{ .Values.hpa.cpu.averageValue }}
        {{- end }}
  {{- end }}
  {{- if .Values.hpa.memory }}
  - type: Resource
    resource:
      name: memory
      target:
        {{- if .Values.hpa.memory.averageUtilization }}
        type: Utilization
        averageUtilization: {{ .Values.hpa.memory.averageUtilization }}
        {{- end }}
        {{- if .Values.hpa.memory.averageValue }}
        type: AverageValue
        averageValue: {{ .Values.hpa.memory.averageValue }}
        {{- end }}
  {{- end }}
  {{- if .Values.hpa.customMetrics }}
{{ toYaml .Values.hpa.customMetrics | indent 2 }}
  {{- end }}
{{- end }}