{{- if .Values.toolchain.httpRoute -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "microfleet.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Values.image.tag | quote }}
spec:
{{ toYaml .Values.toolchain.httpRoute | indent 2 }}
{{- end }}
